### ISSUE TITLE
[Bug]: app completely unusable

### ISSUE THREAD

**Issue by pileton** [friuns2/openclaw-android-assistant#18]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

after upgrading to 2.0.404 not a single feature works, you cant use codex claude or anything

### Steps to reproduce

upgrade to 2.0.404 and nothing will load

### Expected behavior

its supposed to open and work

### Actual behavior

it doesnt open and work

### OpenClaw version

2.0.404

### Operating system

android 16 one ui 8

### Model

gpt 5.4

### Provider / routing chain

idk 

### Logs, screenshots, and evidence

```shell
[codex-web-local] Updating codexui-android@latest in background...
[codex-web-local] Latest update failed (exit_1): npm error code EEXIST
npm error path /usr/local/bin/codexapp
npm error EEXIST: file already exists
npm error File exists: /usr/local/bin/codexapp
npm error Remove the existing file and try again, or run npm
npm error with --force to overwrite files recklessly.
npm error A complete log of this run can be found in: /root/.npm/_logs/2026-04-28T10_13_15_253Z-debug-0.log
[gateway] Foreground service permissions not declared; using in-app fallback
[codex-web-local] Starting on port 18923...
[codex-web-local] Using bundled/local codexui-android for latest
[codex-web-local] node:internal/modules/cjs/loader:1404
[codex-web-local]   throw err;
[codex-web-local]   ^
[codex-web-local] 
[codex-web-local] Error: Cannot find module '/usr/local/lib/node_modules/codexui-android/dist-cli/index.js'
[codex-web-local]     at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
[codex-web-local]     at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
[codex-web-local]     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
[codex-web-local]     at Function._load (node:internal/modules/cjs/loader:1211:37)
[codex-web-local]     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
[codex-web-local]     at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
[codex-web-local]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
[codex-web-local]     at node:internal/main/run_main_module:36:49 {
[codex-web-local]   code: 'MODULE_NOT_FOUND',
[codex-web-local]   requireStack: []
[codex-web-local] }
[codex-web-local] 
[codex-web-local] Node.js v22.16.0
[codex-web-local] Process exited: 1
```

**Comment by friuns2** [comment]
Try new version it's fixed
